---
# copy our war file 
- name: Deploy war file
  sudo: yes
  synchronize: src=/home/kasunr/Downloads/productization.war dest=/var/lib/tomcat7/webapps/ 
  register: war_downloaded

- name: Set correct permissions
  file: 
    path: /var/lib/tomcat7/webapps/productization.war
    owner: tomcat7
    group: tomcat7
    mode: 0755
  when: war_downloaded.changed
  register: war_deployed

- name: Start Tomcat
  service: name=tomcat7 state=restarted enabled=yes 

- name: Set correct permissions app
  file: 
    path: /var/lib/tomcat7/webapps/ROOT
    owner: tomcat7
    group: tomcat7
    recurse: yes
    mode: 0755
  when: war_downloaded.changed
  register: war_deployed
 
